# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=32, unique=True, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='定价')),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='售价')),
                ('pub', models.CharField(max_length=48, verbose_name='出版社')),
            ],
        ),
    ]
